#!/usr/bin/env bash
# Per-boot runtime initialization.
#
# Brings up Docker, starts the local Supabase stack (applying all migrations to
# a fresh database), writes .env.local pointing at that local stack, and seeds
# demo data. Returns once everything is ready; the Next.js dev server runs as a
# separate terminal.
set -euo pipefail

cd "$(dirname "$0")/.."

echo "[start] setting up docker"
bash .cursor/setup-docker.sh

echo "[start] starting local Supabase (applies migrations)"
# Idempotent: no-op if already running.
npx supabase start

echo "[start] writing .env.local from local Supabase status"
STATUS="$(npx supabase status -o env)"
get() { echo "$STATUS" | grep "^$1=" | head -1 | cut -d= -f2- | tr -d '"'; }
API_URL="$(get API_URL)"
PUBLISHABLE_KEY="$(get PUBLISHABLE_KEY)"
SERVICE_ROLE_KEY="$(get SERVICE_ROLE_KEY)"

cat > .env.local <<EOF
# Auto-generated by .cursor/dev-start.sh — points at the local Supabase stack.
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}

# Bunny Stream (video) — placeholders. Real credentials are only needed for
# video playback/upload; the rest of the app works without them.
BUNNY_CDN_HOSTNAME=
BUNNY_CDN_TOKEN_KEY=
BUNNY_LIBRARY_ID=
BUNNY_API_KEY=
BUNNY_SECURITY_KEY=
EOF

echo "[start] seeding demo data"
SUPABASE_URL="${API_URL}" SUPABASE_SERVICE_ROLE_KEY="${SERVICE_ROLE_KEY}" node scripts/seed-dev.mjs || true

echo "[start] ready — run 'npm run dev' (started automatically as a terminal)"
